### PR TITLE
fix: tests fail if persistent database is not empty

### PR DESCRIPTION
**Pull request by socialatm**
Adds a persistent database to run the program
Creates temporary database for testing.
Removes the temporary database on testing restarts.

### CODE REVIEW

**Comment by evanp** [comment]
Hey, thanks for the PR! There's a lot in here. Could you explain what the point is? It sounds like the tests fail if you've got an existing persistent database. Since it writes a lot to the DB, I would really recommend not doing this! What was your point for that?

**Comment by socialatm** [comment]
Thanks for your reply @evanp . With the persistent database if I run `npm test` , let it complete, and then run `npm test`
a second time the second pass always fails. It certainly could be an error on my part or a mistake in my code for sure.
Does it work for you? Thanks

**Comment by evanp** [comment]
I'm pretty sure the tests expect an empty database! I'll take a look.

**Comment by socialatm** [comment]
Hindsight being 20/20 we could just force the tests to use the in memory database to resolve the issue as well. Plus there is a lot that doesn't belong in here due to a code scanning tool I was trying out. If you want to just close this PR I'll send something over that makes more sense. Thanks

**Pull request closed without merging**
